# Generated by Django 2.2.5 on 2019-10-19 22:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RaspNodeConfig', '0002_node_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='User',
            field=models.ForeignKey(null='TRUE', on_delete=django.db.models.deletion.CASCADE, related_name='node', to=settings.AUTH_USER_MODEL),
        ),
    ]
