# Generated by Django 2.2.5 on 2019-10-19 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RaspNodeConfig', '0003_auto_20191020_0032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='node',
            old_name='User',
            new_name='user',
        ),
    ]
