# Generated by Django 2.2.5 on 2019-10-19 22:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('RaspNodeConfig', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='user',
            field=models.ForeignKey(null='TRUE', on_delete=django.db.models.deletion.CASCADE, related_name='node', to=settings.AUTH_USER_MODEL),
            preserve_default='TRUE',
        ),
    ]
