# Generated by Django 2.2.5 on 2019-10-21 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RaspNodeConfig', '0004_auto_20191021_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericcapabilityentry',
            name='node',
            field=models.ForeignKey(blank='TRUE', null='TRUE', on_delete=django.db.models.deletion.CASCADE, related_name='Cap', to='RaspNodeConfig.Node'),
        ),
    ]
